module.exports = {
  "align": false,
  "arrow-parens": false,
  "eofline": false,
  "import-spacing": false,
  "indent": false,
  "linebreak-style": false,
  "max-line-length": false,
  "new-parens": false,
  "no-consecutive-blank-lines": false,
  "no-irregular-whitespace": false,
  "no-trailing-whitespace": false,
  "object-literal-key-quotes": false,
  "one-line": false,
  "quotemark": false,
  "semicolon": false,
  "space-before-function-paren": false,
  "trailing-comma": false,
  "typedef-whitespace": false,
  "whitespace": false,
};
